version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_connections=on"]

  prisma-studio:
    image: node:18
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: >
      bash -c "npm install -g prisma &&
               cd /app &&
               npx prisma studio --hostname 0.0.0.0"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nestjs?schema=public
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data 